before:
  hooks:
    - go mod tidy
    - go generate ./...
    - goimports -w -local "github.com/aretext" .

builds:
  - main: main.go
    binary: aretext
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin

archives:
  - wrap_in_directory: true
    files:
      - LICENSE
      - docs/*

signs:
  - artifacts: checksum
