# aretext configuration

# Each rule below defines a pattern to match the file path.
# All matching rules are merged in-order, with configuration from
# later rules replacing or extending configurations from prior rules.

- name: default
  pattern: "**"
  config:
    autoIndent: false
    hideDirectories: ["**/.git"]
    syntaxLanguage: plaintext
    tabExpand: false
    tabSize: 4
    showTabs: false
    showLineNumbers: false
    styles:
      lineNum: {color: "olive"}
      tokenOperator: {color: "purple"}
      tokenKeyword: {color: "olive"}
      tokenNumber: {color: "green"}
      tokenString: {color: "maroon"}
      tokenComment: {color: "navy"}
#   menuCommands:
#     - name: my custom menu command
#       shellCmd: echo 'hello world!' | less
#       mode: terminal  # or "silent" or "insert" or "fileLocations"

- name: git commit
  pattern: "**/.git/COMMIT_EDITMSG"
  config:
    syntaxLanguage: gitcommit

- name: git rebase
  pattern: "**/.git/**/git-rebase-todo"
  config:
    syntaxLanguage: gitrebase

- name: json
  pattern: "**/*.json"
  config:
    autoIndent: true
    syntaxLanguage: json
    tabExpand: true
    tabSize: 2
    showLineNumbers: true
    styles:
      tokenCustom1: {color: "teal"} # object keys

- name: yaml
  pattern: "**/*.yaml"
  config: &yamlConfig
    autoIndent: true
    syntaxLanguage: yaml
    tabExpand: true
    tabSize: 2
    showLineNumbers: true
    styles:
      tokenCustom1: {color: "teal"} # object keys

- name: yml
  pattern: "**/*.yml"
  config: *yamlConfig

- name: go
  pattern: "**/*.go"
  config:
    autoIndent: true
    syntaxLanguage: go
    tabExpand: false
    tabSize: 4
    showLineNumbers: true

