name: Create a release

on:
  workflow_dispatch:
    inputs:
      majorVersion:
        description: "major version"
        required: true
      minorVersion:
        description: "minor version"
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - uses: actions/checkout@v2
      - id: commit-and-tag
        run: |
          BRANCH="${{ github.event.inputs.majorVersion }}.${{ github.event.inputs.minorVersion }}.x"
          echo "Checking out branch $BRANCH"
          git fetch origin "$BRANCH"
          git checkout "$BRANCH"
          git config user.name aretext-bot
          git config user.email noreply@aretext.org
          VERSION="$(go run main.go -version)"
          echo "Tagging version $VERSION"
          git tag "$VERSION"
          git push origin "$VERSION"
          NEXT_VERSION=$(python -c "major, minor, patch = '$VERSION'.split('.'); print('.'.join([major, minor, str(int(patch)+1)]))")
          echo "Setting next version to $NEXT_VERSION"
          sed -i main.go -e "s/const version =.*/const version = \"${NEXT_VERSION}\"/g"
          git add .
          git commit -m "Set version to ${NEXT_VERSION}"
          git push origin $BRANCH
          echo "::set-output name=version::$VERSION"

      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.commit-and-tag.outputs.version }}
          release_name: ${{ steps.commit-and-tag.outputs.version }}
          draft: true
          prerelease: false
