name: Start release branch

on:
  workflow_dispatch:
    inputs:
      majorVersion:
        description: "major version"
        required: true
      minorVersion:
        description: "minor version"
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          VERSION="${{ github.event.inputs.majorVersion }}.${{ github.event.inputs.minorVersion }}"
          FULL_VERSION="${VERSION}.0"
          BRANCH="${VERSION}.x"
          echo "Updating version in main.go to $FULL_VERSION"
          sed -i main.go -e "s/const version =.*/const version = \"${FULL_VERSION}\"/g"
          echo "Creating branch $BRANCH"
          git checkout -b "$BRANCH"
          git config user.name aretext-bot
          git config user.email noreply@aretext.org
          git add .
          git commit -m "Set version to ${FULL_VERSION}"
          git push origin $BRANCH
